---
- name: Install requrided pakages
  apt:
    name:
      - pip
    update_cache: yes

- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Create gocd folders
  file:
    path: "{{gocd_data_dir}}"
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0777

- name: Create k8s resources
  kubernetes.core.k8s:
    template:
    - ns.yml
    - pv.yml
    - pvc.yml
  become_user: "{{admin_user}}"

- name: Install gocd helm chart
  kubernetes.core.helm:
    release_name: "{{gocd_app_name}}"
    chart_ref: gocd
    chart_repo_url: https://gocd.github.io/helm-chart
    release_namespace: "{{gocd_namespace}}"
    wait: yes
    values_files:
      - /tmp/gocd_values.yml
  become_user: "{{admin_user}}"

- name: Get GoCD server pod name
  kubernetes.core.k8s_info:
    namespace: "{{gocd_namespace}}"
    kind: Pod
  register: godd_pod
  become_user: "{{admin_user}}"

- debug:
    var: godd_pod.resources[0].metadata.name
