---
- name: Install required pakages
  apt:
    name:
      - pip
    update_cache: yes

- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Install gocd helm chart
  kubernetes.core.helm:
    release_name: "{{gocd_app_name}}"
    chart_ref: gocd
    chart_repo_url: https://gocd.github.io/helm-chart
    release_namespace: "{{gocd_namespace}}"
    create_namespace: true
    wait: yes
    values_files:
      - /tmp/gocd_values.yml
  become_user: "{{admin_user}}"

- name: Get GoCD server pod name
  kubernetes.core.k8s_info:
    namespace: "{{gocd_namespace}}"
    kind: Pod
  register: gocd_pod
  become_user: "{{admin_user}}"

- name: Initialize GoCD secrets file
  kubernetes.core.k8s_exec:
    namespace: "{{gocd_namespace}}"
    pod: "{{gocd_pod.resources[0].metadata.name}}"
    command: /gocd-jre/bin/java -jar /godata/plugins/bundled/gocd-file-based-secrets-plugin.jar init -f /godata/config/secrets.json
  become_user: "{{admin_user}}"

