apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{pv_name}}
  labels:
    type: local
spec:
  storageClassName: {{storage_class_name}}
  capacity:
    storage: {{pv_storage_size}}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{gocd_data_dir}}
