#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: {{gocd_pv_name}}
#  labels:
#    type: local
#spec:
#  storageClassName: {{storage_class_name}}
#  capacity:
#    storage: {{gocd_pv_storage_size}}
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: {{gocd_data_dir}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-config
  labels:
    type: local
spec:
  storageClassName: {{storage_class_name}}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/local/share/docker-config
