apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{pvc_name}}
  namespace: {{k8s_namespace}}
spec:
  storageClassName: {{storage_class_name}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{pvc_size}}
